// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package archsqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.getSporttiIDsStmt, err = db.PrepareContext(ctx, getSporttiIDs); err != nil {
		return nil, fmt.Errorf("error preparing query GetSporttiIDs: %w", err)
	}
	if q.insertAthleteStmt, err = db.PrepareContext(ctx, insertAthlete); err != nil {
		return nil, fmt.Errorf("error preparing query InsertAthlete: %w", err)
	}
	if q.insertMeasurementStmt, err = db.PrepareContext(ctx, insertMeasurement); err != nil {
		return nil, fmt.Errorf("error preparing query InsertMeasurement: %w", err)
	}
	if q.insertRaceReportStmt, err = db.PrepareContext(ctx, insertRaceReport); err != nil {
		return nil, fmt.Errorf("error preparing query InsertRaceReport: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.getSporttiIDsStmt != nil {
		if cerr := q.getSporttiIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSporttiIDsStmt: %w", cerr)
		}
	}
	if q.insertAthleteStmt != nil {
		if cerr := q.insertAthleteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertAthleteStmt: %w", cerr)
		}
	}
	if q.insertMeasurementStmt != nil {
		if cerr := q.insertMeasurementStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertMeasurementStmt: %w", cerr)
		}
	}
	if q.insertRaceReportStmt != nil {
		if cerr := q.insertRaceReportStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertRaceReportStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                    DBTX
	tx                    *sql.Tx
	getSporttiIDsStmt     *sql.Stmt
	insertAthleteStmt     *sql.Stmt
	insertMeasurementStmt *sql.Stmt
	insertRaceReportStmt  *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                    tx,
		tx:                    tx,
		getSporttiIDsStmt:     q.getSporttiIDsStmt,
		insertAthleteStmt:     q.insertAthleteStmt,
		insertMeasurementStmt: q.insertMeasurementStmt,
		insertRaceReportStmt:  q.insertRaceReportStmt,
	}
}
