// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package archsqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.deleteAthleteByNationalIDStmt, err = db.PrepareContext(ctx, deleteAthleteByNationalID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAthleteByNationalID: %w", err)
	}
	if q.getAthleteBySporttiIDStmt, err = db.PrepareContext(ctx, getAthleteBySporttiID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAthleteBySporttiID: %w", err)
	}
	if q.getMeasurementsBySporttiIDStmt, err = db.PrepareContext(ctx, getMeasurementsBySporttiID); err != nil {
		return nil, fmt.Errorf("error preparing query GetMeasurementsBySporttiID: %w", err)
	}
	if q.getRaceReportStmt, err = db.PrepareContext(ctx, getRaceReport); err != nil {
		return nil, fmt.Errorf("error preparing query GetRaceReport: %w", err)
	}
	if q.getRaceReportSessionIDsBySporttiIDStmt, err = db.PrepareContext(ctx, getRaceReportSessionIDsBySporttiID); err != nil {
		return nil, fmt.Errorf("error preparing query GetRaceReportSessionIDsBySporttiID: %w", err)
	}
	if q.upsertAthleteStmt, err = db.PrepareContext(ctx, upsertAthlete); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertAthlete: %w", err)
	}
	if q.upsertMeasurementStmt, err = db.PrepareContext(ctx, upsertMeasurement); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertMeasurement: %w", err)
	}
	if q.upsertRaceReportStmt, err = db.PrepareContext(ctx, upsertRaceReport); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertRaceReport: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.deleteAthleteByNationalIDStmt != nil {
		if cerr := q.deleteAthleteByNationalIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAthleteByNationalIDStmt: %w", cerr)
		}
	}
	if q.getAthleteBySporttiIDStmt != nil {
		if cerr := q.getAthleteBySporttiIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAthleteBySporttiIDStmt: %w", cerr)
		}
	}
	if q.getMeasurementsBySporttiIDStmt != nil {
		if cerr := q.getMeasurementsBySporttiIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMeasurementsBySporttiIDStmt: %w", cerr)
		}
	}
	if q.getRaceReportStmt != nil {
		if cerr := q.getRaceReportStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRaceReportStmt: %w", cerr)
		}
	}
	if q.getRaceReportSessionIDsBySporttiIDStmt != nil {
		if cerr := q.getRaceReportSessionIDsBySporttiIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRaceReportSessionIDsBySporttiIDStmt: %w", cerr)
		}
	}
	if q.upsertAthleteStmt != nil {
		if cerr := q.upsertAthleteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertAthleteStmt: %w", cerr)
		}
	}
	if q.upsertMeasurementStmt != nil {
		if cerr := q.upsertMeasurementStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertMeasurementStmt: %w", cerr)
		}
	}
	if q.upsertRaceReportStmt != nil {
		if cerr := q.upsertRaceReportStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertRaceReportStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                     DBTX
	tx                                     *sql.Tx
	deleteAthleteByNationalIDStmt          *sql.Stmt
	getAthleteBySporttiIDStmt              *sql.Stmt
	getMeasurementsBySporttiIDStmt         *sql.Stmt
	getRaceReportStmt                      *sql.Stmt
	getRaceReportSessionIDsBySporttiIDStmt *sql.Stmt
	upsertAthleteStmt                      *sql.Stmt
	upsertMeasurementStmt                  *sql.Stmt
	upsertRaceReportStmt                   *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                     tx,
		tx:                                     tx,
		deleteAthleteByNationalIDStmt:          q.deleteAthleteByNationalIDStmt,
		getAthleteBySporttiIDStmt:              q.getAthleteBySporttiIDStmt,
		getMeasurementsBySporttiIDStmt:         q.getMeasurementsBySporttiIDStmt,
		getRaceReportStmt:                      q.getRaceReportStmt,
		getRaceReportSessionIDsBySporttiIDStmt: q.getRaceReportSessionIDsBySporttiIDStmt,
		upsertAthleteStmt:                      q.upsertAthleteStmt,
		upsertMeasurementStmt:                  q.upsertMeasurementStmt,
		upsertRaceReportStmt:                   q.upsertRaceReportStmt,
	}
}
