// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package archsqlc

import (
	"database/sql"
)

type Athlete struct {
	NationalID  string
	FirstName   sql.NullString
	LastName    sql.NullString
	Initials    sql.NullString
	DateOfBirth sql.NullTime
	Height      sql.NullString
	Weight      sql.NullString
}

type Measurement struct {
	MeasurementGroupID sql.NullInt32
	MeasurementID      int32
	NationalID         sql.NullString
	Discipline         sql.NullString
	SessionName        sql.NullString
	Place              sql.NullString
	RaceID             sql.NullInt32
	StartTime          sql.NullTime
	StopTime           sql.NullTime
	NbSegments         sql.NullInt32
	Comment            sql.NullString
}

type MeasurementGroup struct {
	MeasurementGroupID int32
}

type Report struct {
	ReportID   int32
	SporttiID  sql.NullString
	SessionID  sql.NullInt32
	RaceReport sql.NullString
}
