// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package archsqlc

import (
	"context"
	"database/sql"
)

const getSporttiIDs = `-- name: GetSporttiIDs :many
SELECT sportti_id FROM sportti_id_list
`

func (q *Queries) GetSporttiIDs(ctx context.Context) ([]string, error) {
	rows, err := q.query(ctx, q.getSporttiIDsStmt, getSporttiIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var sportti_id string
		if err := rows.Scan(&sportti_id); err != nil {
			return nil, err
		}
		items = append(items, sportti_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAthlete = `-- name: InsertAthlete :exec
INSERT INTO athlete (
  national_id, first_name, last_name, initials,
  date_of_birth, height, weight
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7
)
ON CONFLICT (national_id) DO NOTHING
`

type InsertAthleteParams struct {
	NationalID  string
	FirstName   sql.NullString
	LastName    sql.NullString
	Initials    sql.NullString
	DateOfBirth sql.NullTime
	Height      sql.NullString
	Weight      sql.NullString
}

func (q *Queries) InsertAthlete(ctx context.Context, arg InsertAthleteParams) error {
	_, err := q.exec(ctx, q.insertAthleteStmt, insertAthlete,
		arg.NationalID,
		arg.FirstName,
		arg.LastName,
		arg.Initials,
		arg.DateOfBirth,
		arg.Height,
		arg.Weight,
	)
	return err
}

const insertMeasurement = `-- name: InsertMeasurement :exec
INSERT INTO measurement (
  measurement_group_id, measurement_id, national_id,
  discipline, session_name, place, race_id,
  start_time, stop_time, nb_segments, comment
) VALUES (
  $1, $2, $3,
  $4, $5, $6, $7,
  $8, $9, $10, $11
)
ON CONFLICT (measurement_group_id) DO NOTHING
`

type InsertMeasurementParams struct {
	MeasurementGroupID int32
	MeasurementID      sql.NullInt32
	NationalID         sql.NullString
	Discipline         sql.NullString
	SessionName        sql.NullString
	Place              sql.NullString
	RaceID             sql.NullInt32
	StartTime          sql.NullTime
	StopTime           sql.NullTime
	NbSegments         sql.NullInt32
	Comment            sql.NullString
}

func (q *Queries) InsertMeasurement(ctx context.Context, arg InsertMeasurementParams) error {
	_, err := q.exec(ctx, q.insertMeasurementStmt, insertMeasurement,
		arg.MeasurementGroupID,
		arg.MeasurementID,
		arg.NationalID,
		arg.Discipline,
		arg.SessionName,
		arg.Place,
		arg.RaceID,
		arg.StartTime,
		arg.StopTime,
		arg.NbSegments,
		arg.Comment,
	)
	return err
}

const insertRaceReport = `-- name: InsertRaceReport :exec
INSERT INTO report (
  sportti_id, session_id, race_report
) VALUES (
  $1, $2, $3
)
ON CONFLICT (report_id) DO NOTHING
`

type InsertRaceReportParams struct {
	SporttiID  sql.NullString
	SessionID  sql.NullInt32
	RaceReport sql.NullString
}

func (q *Queries) InsertRaceReport(ctx context.Context, arg InsertRaceReportParams) error {
	_, err := q.exec(ctx, q.insertRaceReportStmt, insertRaceReport, arg.SporttiID, arg.SessionID, arg.RaceReport)
	return err
}
