// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package klabsqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.getAllSporttiIDsStmt, err = db.PrepareContext(ctx, getAllSporttiIDs); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllSporttiIDs: %w", err)
	}
	if q.getCustomerByIDStmt, err = db.PrepareContext(ctx, getCustomerByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCustomerByID: %w", err)
	}
	if q.getCustomerIDBySporttiIDStmt, err = db.PrepareContext(ctx, getCustomerIDBySporttiID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCustomerIDBySporttiID: %w", err)
	}
	if q.getDirRawDataByMeasurementIDsStmt, err = db.PrepareContext(ctx, getDirRawDataByMeasurementIDs); err != nil {
		return nil, fmt.Errorf("error preparing query GetDirRawDataByMeasurementIDs: %w", err)
	}
	if q.getDirReportsByMeasurementIDsStmt, err = db.PrepareContext(ctx, getDirReportsByMeasurementIDs); err != nil {
		return nil, fmt.Errorf("error preparing query GetDirReportsByMeasurementIDs: %w", err)
	}
	if q.getDirResultsByMeasurementIDsStmt, err = db.PrepareContext(ctx, getDirResultsByMeasurementIDs); err != nil {
		return nil, fmt.Errorf("error preparing query GetDirResultsByMeasurementIDs: %w", err)
	}
	if q.getDirTestStepsByMeasurementIDsStmt, err = db.PrepareContext(ctx, getDirTestStepsByMeasurementIDs); err != nil {
		return nil, fmt.Errorf("error preparing query GetDirTestStepsByMeasurementIDs: %w", err)
	}
	if q.getDirTestsByMeasurementIDsStmt, err = db.PrepareContext(ctx, getDirTestsByMeasurementIDs); err != nil {
		return nil, fmt.Errorf("error preparing query GetDirTestsByMeasurementIDs: %w", err)
	}
	if q.getMeasurementsByCustomerStmt, err = db.PrepareContext(ctx, getMeasurementsByCustomer); err != nil {
		return nil, fmt.Errorf("error preparing query GetMeasurementsByCustomer: %w", err)
	}
	if q.insertDirRawDataStmt, err = db.PrepareContext(ctx, insertDirRawData); err != nil {
		return nil, fmt.Errorf("error preparing query InsertDirRawData: %w", err)
	}
	if q.insertDirReportStmt, err = db.PrepareContext(ctx, insertDirReport); err != nil {
		return nil, fmt.Errorf("error preparing query InsertDirReport: %w", err)
	}
	if q.insertDirResultsStmt, err = db.PrepareContext(ctx, insertDirResults); err != nil {
		return nil, fmt.Errorf("error preparing query InsertDirResults: %w", err)
	}
	if q.insertDirTestStmt, err = db.PrepareContext(ctx, insertDirTest); err != nil {
		return nil, fmt.Errorf("error preparing query InsertDirTest: %w", err)
	}
	if q.insertDirTestStepStmt, err = db.PrepareContext(ctx, insertDirTestStep); err != nil {
		return nil, fmt.Errorf("error preparing query InsertDirTestStep: %w", err)
	}
	if q.insertMeasurementStmt, err = db.PrepareContext(ctx, insertMeasurement); err != nil {
		return nil, fmt.Errorf("error preparing query InsertMeasurement: %w", err)
	}
	if q.upsertCustomerStmt, err = db.PrepareContext(ctx, upsertCustomer); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertCustomer: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.getAllSporttiIDsStmt != nil {
		if cerr := q.getAllSporttiIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllSporttiIDsStmt: %w", cerr)
		}
	}
	if q.getCustomerByIDStmt != nil {
		if cerr := q.getCustomerByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCustomerByIDStmt: %w", cerr)
		}
	}
	if q.getCustomerIDBySporttiIDStmt != nil {
		if cerr := q.getCustomerIDBySporttiIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCustomerIDBySporttiIDStmt: %w", cerr)
		}
	}
	if q.getDirRawDataByMeasurementIDsStmt != nil {
		if cerr := q.getDirRawDataByMeasurementIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDirRawDataByMeasurementIDsStmt: %w", cerr)
		}
	}
	if q.getDirReportsByMeasurementIDsStmt != nil {
		if cerr := q.getDirReportsByMeasurementIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDirReportsByMeasurementIDsStmt: %w", cerr)
		}
	}
	if q.getDirResultsByMeasurementIDsStmt != nil {
		if cerr := q.getDirResultsByMeasurementIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDirResultsByMeasurementIDsStmt: %w", cerr)
		}
	}
	if q.getDirTestStepsByMeasurementIDsStmt != nil {
		if cerr := q.getDirTestStepsByMeasurementIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDirTestStepsByMeasurementIDsStmt: %w", cerr)
		}
	}
	if q.getDirTestsByMeasurementIDsStmt != nil {
		if cerr := q.getDirTestsByMeasurementIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDirTestsByMeasurementIDsStmt: %w", cerr)
		}
	}
	if q.getMeasurementsByCustomerStmt != nil {
		if cerr := q.getMeasurementsByCustomerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMeasurementsByCustomerStmt: %w", cerr)
		}
	}
	if q.insertDirRawDataStmt != nil {
		if cerr := q.insertDirRawDataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertDirRawDataStmt: %w", cerr)
		}
	}
	if q.insertDirReportStmt != nil {
		if cerr := q.insertDirReportStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertDirReportStmt: %w", cerr)
		}
	}
	if q.insertDirResultsStmt != nil {
		if cerr := q.insertDirResultsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertDirResultsStmt: %w", cerr)
		}
	}
	if q.insertDirTestStmt != nil {
		if cerr := q.insertDirTestStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertDirTestStmt: %w", cerr)
		}
	}
	if q.insertDirTestStepStmt != nil {
		if cerr := q.insertDirTestStepStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertDirTestStepStmt: %w", cerr)
		}
	}
	if q.insertMeasurementStmt != nil {
		if cerr := q.insertMeasurementStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertMeasurementStmt: %w", cerr)
		}
	}
	if q.upsertCustomerStmt != nil {
		if cerr := q.upsertCustomerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertCustomerStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                  DBTX
	tx                                  *sql.Tx
	getAllSporttiIDsStmt                *sql.Stmt
	getCustomerByIDStmt                 *sql.Stmt
	getCustomerIDBySporttiIDStmt        *sql.Stmt
	getDirRawDataByMeasurementIDsStmt   *sql.Stmt
	getDirReportsByMeasurementIDsStmt   *sql.Stmt
	getDirResultsByMeasurementIDsStmt   *sql.Stmt
	getDirTestStepsByMeasurementIDsStmt *sql.Stmt
	getDirTestsByMeasurementIDsStmt     *sql.Stmt
	getMeasurementsByCustomerStmt       *sql.Stmt
	insertDirRawDataStmt                *sql.Stmt
	insertDirReportStmt                 *sql.Stmt
	insertDirResultsStmt                *sql.Stmt
	insertDirTestStmt                   *sql.Stmt
	insertDirTestStepStmt               *sql.Stmt
	insertMeasurementStmt               *sql.Stmt
	upsertCustomerStmt                  *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                  tx,
		tx:                                  tx,
		getAllSporttiIDsStmt:                q.getAllSporttiIDsStmt,
		getCustomerByIDStmt:                 q.getCustomerByIDStmt,
		getCustomerIDBySporttiIDStmt:        q.getCustomerIDBySporttiIDStmt,
		getDirRawDataByMeasurementIDsStmt:   q.getDirRawDataByMeasurementIDsStmt,
		getDirReportsByMeasurementIDsStmt:   q.getDirReportsByMeasurementIDsStmt,
		getDirResultsByMeasurementIDsStmt:   q.getDirResultsByMeasurementIDsStmt,
		getDirTestStepsByMeasurementIDsStmt: q.getDirTestStepsByMeasurementIDsStmt,
		getDirTestsByMeasurementIDsStmt:     q.getDirTestsByMeasurementIDsStmt,
		getMeasurementsByCustomerStmt:       q.getMeasurementsByCustomerStmt,
		insertDirRawDataStmt:                q.insertDirRawDataStmt,
		insertDirReportStmt:                 q.insertDirReportStmt,
		insertDirResultsStmt:                q.insertDirResultsStmt,
		insertDirTestStmt:                   q.insertDirTestStmt,
		insertDirTestStepStmt:               q.insertDirTestStepStmt,
		insertMeasurementStmt:               q.insertMeasurementStmt,
		upsertCustomerStmt:                  q.upsertCustomerStmt,
	}
}
