// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package authsqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addClientRoleStmt, err = db.PrepareContext(ctx, addClientRole); err != nil {
		return nil, fmt.Errorf("error preparing query AddClientRole: %w", err)
	}
	if q.createClientStmt, err = db.PrepareContext(ctx, createClient); err != nil {
		return nil, fmt.Errorf("error preparing query CreateClient: %w", err)
	}
	if q.createRefreshTokenStmt, err = db.PrepareContext(ctx, createRefreshToken); err != nil {
		return nil, fmt.Errorf("error preparing query CreateRefreshToken: %w", err)
	}
	if q.createRevokedRefreshTokenStmt, err = db.PrepareContext(ctx, createRevokedRefreshToken); err != nil {
		return nil, fmt.Errorf("error preparing query CreateRevokedRefreshToken: %w", err)
	}
	if q.createRevokedTokenStmt, err = db.PrepareContext(ctx, createRevokedToken); err != nil {
		return nil, fmt.Errorf("error preparing query CreateRevokedToken: %w", err)
	}
	if q.deleteAllRefreshTokensForClientStmt, err = db.PrepareContext(ctx, deleteAllRefreshTokensForClient); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllRefreshTokensForClient: %w", err)
	}
	if q.deleteClientStmt, err = db.PrepareContext(ctx, deleteClient); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteClient: %w", err)
	}
	if q.deleteExpiredRefreshTokensStmt, err = db.PrepareContext(ctx, deleteExpiredRefreshTokens); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteExpiredRefreshTokens: %w", err)
	}
	if q.deleteRefreshTokenStmt, err = db.PrepareContext(ctx, deleteRefreshToken); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteRefreshToken: %w", err)
	}
	if q.deleteRefreshTokenByTokenStmt, err = db.PrepareContext(ctx, deleteRefreshTokenByToken); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteRefreshTokenByToken: %w", err)
	}
	if q.deleteRevokedRefreshTokenStmt, err = db.PrepareContext(ctx, deleteRevokedRefreshToken); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteRevokedRefreshToken: %w", err)
	}
	if q.deleteRevokedTokenStmt, err = db.PrepareContext(ctx, deleteRevokedToken); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteRevokedToken: %w", err)
	}
	if q.getClientByNameStmt, err = db.PrepareContext(ctx, getClientByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetClientByName: %w", err)
	}
	if q.getClientByTokenStmt, err = db.PrepareContext(ctx, getClientByToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetClientByToken: %w", err)
	}
	if q.getClientRolesStmt, err = db.PrepareContext(ctx, getClientRoles); err != nil {
		return nil, fmt.Errorf("error preparing query GetClientRoles: %w", err)
	}
	if q.getClientsByRoleStmt, err = db.PrepareContext(ctx, getClientsByRole); err != nil {
		return nil, fmt.Errorf("error preparing query GetClientsByRole: %w", err)
	}
	if q.getLogsByActionStmt, err = db.PrepareContext(ctx, getLogsByAction); err != nil {
		return nil, fmt.Errorf("error preparing query GetLogsByAction: %w", err)
	}
	if q.getLogsByClientStmt, err = db.PrepareContext(ctx, getLogsByClient); err != nil {
		return nil, fmt.Errorf("error preparing query GetLogsByClient: %w", err)
	}
	if q.getLogsByTokenTypeStmt, err = db.PrepareContext(ctx, getLogsByTokenType); err != nil {
		return nil, fmt.Errorf("error preparing query GetLogsByTokenType: %w", err)
	}
	if q.getRefreshTokenStmt, err = db.PrepareContext(ctx, getRefreshToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetRefreshToken: %w", err)
	}
	if q.getRefreshTokenByClientStmt, err = db.PrepareContext(ctx, getRefreshTokenByClient); err != nil {
		return nil, fmt.Errorf("error preparing query GetRefreshTokenByClient: %w", err)
	}
	if q.hasRoleStmt, err = db.PrepareContext(ctx, hasRole); err != nil {
		return nil, fmt.Errorf("error preparing query HasRole: %w", err)
	}
	if q.insertNewRefreshTokenStmt, err = db.PrepareContext(ctx, insertNewRefreshToken); err != nil {
		return nil, fmt.Errorf("error preparing query InsertNewRefreshToken: %w", err)
	}
	if q.insertRevokedRefreshTokenStmt, err = db.PrepareContext(ctx, insertRevokedRefreshToken); err != nil {
		return nil, fmt.Errorf("error preparing query InsertRevokedRefreshToken: %w", err)
	}
	if q.insertTokenLogStmt, err = db.PrepareContext(ctx, insertTokenLog); err != nil {
		return nil, fmt.Errorf("error preparing query InsertTokenLog: %w", err)
	}
	if q.isRefreshTokenExpiredStmt, err = db.PrepareContext(ctx, isRefreshTokenExpired); err != nil {
		return nil, fmt.Errorf("error preparing query IsRefreshTokenExpired: %w", err)
	}
	if q.isRevokedRefreshTokenStmt, err = db.PrepareContext(ctx, isRevokedRefreshToken); err != nil {
		return nil, fmt.Errorf("error preparing query IsRevokedRefreshToken: %w", err)
	}
	if q.isRevokedTokenStmt, err = db.PrepareContext(ctx, isRevokedToken); err != nil {
		return nil, fmt.Errorf("error preparing query IsRevokedToken: %w", err)
	}
	if q.listClientsStmt, err = db.PrepareContext(ctx, listClients); err != nil {
		return nil, fmt.Errorf("error preparing query ListClients: %w", err)
	}
	if q.removeClientRoleStmt, err = db.PrepareContext(ctx, removeClientRole); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveClientRole: %w", err)
	}
	if q.updateClientRolesStmt, err = db.PrepareContext(ctx, updateClientRoles); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateClientRoles: %w", err)
	}
	if q.updateClientTokenStmt, err = db.PrepareContext(ctx, updateClientToken); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateClientToken: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addClientRoleStmt != nil {
		if cerr := q.addClientRoleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addClientRoleStmt: %w", cerr)
		}
	}
	if q.createClientStmt != nil {
		if cerr := q.createClientStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createClientStmt: %w", cerr)
		}
	}
	if q.createRefreshTokenStmt != nil {
		if cerr := q.createRefreshTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createRefreshTokenStmt: %w", cerr)
		}
	}
	if q.createRevokedRefreshTokenStmt != nil {
		if cerr := q.createRevokedRefreshTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createRevokedRefreshTokenStmt: %w", cerr)
		}
	}
	if q.createRevokedTokenStmt != nil {
		if cerr := q.createRevokedTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createRevokedTokenStmt: %w", cerr)
		}
	}
	if q.deleteAllRefreshTokensForClientStmt != nil {
		if cerr := q.deleteAllRefreshTokensForClientStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllRefreshTokensForClientStmt: %w", cerr)
		}
	}
	if q.deleteClientStmt != nil {
		if cerr := q.deleteClientStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteClientStmt: %w", cerr)
		}
	}
	if q.deleteExpiredRefreshTokensStmt != nil {
		if cerr := q.deleteExpiredRefreshTokensStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteExpiredRefreshTokensStmt: %w", cerr)
		}
	}
	if q.deleteRefreshTokenStmt != nil {
		if cerr := q.deleteRefreshTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteRefreshTokenStmt: %w", cerr)
		}
	}
	if q.deleteRefreshTokenByTokenStmt != nil {
		if cerr := q.deleteRefreshTokenByTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteRefreshTokenByTokenStmt: %w", cerr)
		}
	}
	if q.deleteRevokedRefreshTokenStmt != nil {
		if cerr := q.deleteRevokedRefreshTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteRevokedRefreshTokenStmt: %w", cerr)
		}
	}
	if q.deleteRevokedTokenStmt != nil {
		if cerr := q.deleteRevokedTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteRevokedTokenStmt: %w", cerr)
		}
	}
	if q.getClientByNameStmt != nil {
		if cerr := q.getClientByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getClientByNameStmt: %w", cerr)
		}
	}
	if q.getClientByTokenStmt != nil {
		if cerr := q.getClientByTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getClientByTokenStmt: %w", cerr)
		}
	}
	if q.getClientRolesStmt != nil {
		if cerr := q.getClientRolesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getClientRolesStmt: %w", cerr)
		}
	}
	if q.getClientsByRoleStmt != nil {
		if cerr := q.getClientsByRoleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getClientsByRoleStmt: %w", cerr)
		}
	}
	if q.getLogsByActionStmt != nil {
		if cerr := q.getLogsByActionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLogsByActionStmt: %w", cerr)
		}
	}
	if q.getLogsByClientStmt != nil {
		if cerr := q.getLogsByClientStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLogsByClientStmt: %w", cerr)
		}
	}
	if q.getLogsByTokenTypeStmt != nil {
		if cerr := q.getLogsByTokenTypeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLogsByTokenTypeStmt: %w", cerr)
		}
	}
	if q.getRefreshTokenStmt != nil {
		if cerr := q.getRefreshTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRefreshTokenStmt: %w", cerr)
		}
	}
	if q.getRefreshTokenByClientStmt != nil {
		if cerr := q.getRefreshTokenByClientStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRefreshTokenByClientStmt: %w", cerr)
		}
	}
	if q.hasRoleStmt != nil {
		if cerr := q.hasRoleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing hasRoleStmt: %w", cerr)
		}
	}
	if q.insertNewRefreshTokenStmt != nil {
		if cerr := q.insertNewRefreshTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertNewRefreshTokenStmt: %w", cerr)
		}
	}
	if q.insertRevokedRefreshTokenStmt != nil {
		if cerr := q.insertRevokedRefreshTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertRevokedRefreshTokenStmt: %w", cerr)
		}
	}
	if q.insertTokenLogStmt != nil {
		if cerr := q.insertTokenLogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertTokenLogStmt: %w", cerr)
		}
	}
	if q.isRefreshTokenExpiredStmt != nil {
		if cerr := q.isRefreshTokenExpiredStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing isRefreshTokenExpiredStmt: %w", cerr)
		}
	}
	if q.isRevokedRefreshTokenStmt != nil {
		if cerr := q.isRevokedRefreshTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing isRevokedRefreshTokenStmt: %w", cerr)
		}
	}
	if q.isRevokedTokenStmt != nil {
		if cerr := q.isRevokedTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing isRevokedTokenStmt: %w", cerr)
		}
	}
	if q.listClientsStmt != nil {
		if cerr := q.listClientsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listClientsStmt: %w", cerr)
		}
	}
	if q.removeClientRoleStmt != nil {
		if cerr := q.removeClientRoleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeClientRoleStmt: %w", cerr)
		}
	}
	if q.updateClientRolesStmt != nil {
		if cerr := q.updateClientRolesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateClientRolesStmt: %w", cerr)
		}
	}
	if q.updateClientTokenStmt != nil {
		if cerr := q.updateClientTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateClientTokenStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                  DBTX
	tx                                  *sql.Tx
	addClientRoleStmt                   *sql.Stmt
	createClientStmt                    *sql.Stmt
	createRefreshTokenStmt              *sql.Stmt
	createRevokedRefreshTokenStmt       *sql.Stmt
	createRevokedTokenStmt              *sql.Stmt
	deleteAllRefreshTokensForClientStmt *sql.Stmt
	deleteClientStmt                    *sql.Stmt
	deleteExpiredRefreshTokensStmt      *sql.Stmt
	deleteRefreshTokenStmt              *sql.Stmt
	deleteRefreshTokenByTokenStmt       *sql.Stmt
	deleteRevokedRefreshTokenStmt       *sql.Stmt
	deleteRevokedTokenStmt              *sql.Stmt
	getClientByNameStmt                 *sql.Stmt
	getClientByTokenStmt                *sql.Stmt
	getClientRolesStmt                  *sql.Stmt
	getClientsByRoleStmt                *sql.Stmt
	getLogsByActionStmt                 *sql.Stmt
	getLogsByClientStmt                 *sql.Stmt
	getLogsByTokenTypeStmt              *sql.Stmt
	getRefreshTokenStmt                 *sql.Stmt
	getRefreshTokenByClientStmt         *sql.Stmt
	hasRoleStmt                         *sql.Stmt
	insertNewRefreshTokenStmt           *sql.Stmt
	insertRevokedRefreshTokenStmt       *sql.Stmt
	insertTokenLogStmt                  *sql.Stmt
	isRefreshTokenExpiredStmt           *sql.Stmt
	isRevokedRefreshTokenStmt           *sql.Stmt
	isRevokedTokenStmt                  *sql.Stmt
	listClientsStmt                     *sql.Stmt
	removeClientRoleStmt                *sql.Stmt
	updateClientRolesStmt               *sql.Stmt
	updateClientTokenStmt               *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                  tx,
		tx:                                  tx,
		addClientRoleStmt:                   q.addClientRoleStmt,
		createClientStmt:                    q.createClientStmt,
		createRefreshTokenStmt:              q.createRefreshTokenStmt,
		createRevokedRefreshTokenStmt:       q.createRevokedRefreshTokenStmt,
		createRevokedTokenStmt:              q.createRevokedTokenStmt,
		deleteAllRefreshTokensForClientStmt: q.deleteAllRefreshTokensForClientStmt,
		deleteClientStmt:                    q.deleteClientStmt,
		deleteExpiredRefreshTokensStmt:      q.deleteExpiredRefreshTokensStmt,
		deleteRefreshTokenStmt:              q.deleteRefreshTokenStmt,
		deleteRefreshTokenByTokenStmt:       q.deleteRefreshTokenByTokenStmt,
		deleteRevokedRefreshTokenStmt:       q.deleteRevokedRefreshTokenStmt,
		deleteRevokedTokenStmt:              q.deleteRevokedTokenStmt,
		getClientByNameStmt:                 q.getClientByNameStmt,
		getClientByTokenStmt:                q.getClientByTokenStmt,
		getClientRolesStmt:                  q.getClientRolesStmt,
		getClientsByRoleStmt:                q.getClientsByRoleStmt,
		getLogsByActionStmt:                 q.getLogsByActionStmt,
		getLogsByClientStmt:                 q.getLogsByClientStmt,
		getLogsByTokenTypeStmt:              q.getLogsByTokenTypeStmt,
		getRefreshTokenStmt:                 q.getRefreshTokenStmt,
		getRefreshTokenByClientStmt:         q.getRefreshTokenByClientStmt,
		hasRoleStmt:                         q.hasRoleStmt,
		insertNewRefreshTokenStmt:           q.insertNewRefreshTokenStmt,
		insertRevokedRefreshTokenStmt:       q.insertRevokedRefreshTokenStmt,
		insertTokenLogStmt:                  q.insertTokenLogStmt,
		isRefreshTokenExpiredStmt:           q.isRefreshTokenExpiredStmt,
		isRevokedRefreshTokenStmt:           q.isRevokedRefreshTokenStmt,
		isRevokedTokenStmt:                  q.isRevokedTokenStmt,
		listClientsStmt:                     q.listClientsStmt,
		removeClientRoleStmt:                q.removeClientRoleStmt,
		updateClientRolesStmt:               q.updateClientRolesStmt,
		updateClientTokenStmt:               q.updateClientTokenStmt,
	}
}
