// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package authsqlc

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Client struct {
	ID          int32
	ClientName  string
	ClientToken string
	Role        []string
	CreatedAt   sql.NullTime
}

type RefreshToken struct {
	ID          int32
	ClientToken string
	Token       string
	ExpiresAt   time.Time
	CreatedAt   sql.NullTime
}

type RevokedRefreshToken struct {
	Token     string
	RevokedAt sql.NullTime
}

type RevokedToken struct {
	ClientToken string
	RevokedAt   sql.NullTime
}

type TokenLog struct {
	ID          int32
	ClientToken string
	TokenType   string
	Action      string
	Token       sql.NullString
	IpAddress   sql.NullString
	UserAgent   sql.NullString
	Metadata    pqtype.NullRawMessage
	CreatedAt   sql.NullTime
}
