
--
-- Name: a_competitor; Type: TABLE; Schema: public; Owner: fislocal
--

CREATE TABLE public.a_competitor (
    competitorid integer,
    personid integer,
    ipcid integer,
    type character varying(255),
    sectorcode character varying(255),
    fiscode integer,
    lastname character varying(255),
    firstname character varying(255),
    gender character(1),
    birthdate date,
    nationcode character varying(255),
    nationalcode character varying(255),
    skiclub character varying(255),
    association character varying(255),
    status character varying(255),
    status_old character varying(255),
    status_by character varying(255),
    status_date timestamp without time zone,
    statusnextlist character varying(255),
    alternatenamecheck character varying(255),
    fee numeric(10,5),
    dateofcreation date,
    createdby character varying(255),
    injury integer,
    version integer,
    compidmssql integer,
    carving integer,
    photo integer,
    notallowed integer,
    natteam character varying(255),
    tragroup character varying(255),
    published integer,
    doped character varying(255),
    team integer,
    photo_big integer,
    data character varying(1000),
    lastupdateby character varying(255),
    disciplines character varying(1000),
    lastupdate timestamp without time zone
);


--
-- Name: a_racejp; Type: TABLE; Schema: public; Owner: fislocal
--

CREATE TABLE public.a_racejp (
    raceid integer,
    eventid integer,
    seasoncode integer,
    racecodex integer,
    disciplineid character varying(255),
    disciplinecode character varying(255),
    catcode character varying(255),
    catcode2 character varying(255),
    catcode3 character varying(255),
    catcode4 character varying(255),
    gender character varying(255),
    racedate date,
    starteventdate date,
    description character varying(255),
    place character varying(255),
    nationcode character varying(255),
    td1id integer,
    td1name character varying(255),
    td1nation character varying(255),
    td1code integer,
    td2id integer,
    td2name character varying(255),
    td2nation character varying(255),
    td2code integer,
    calstatuscode character varying(255),
    procstatuscode character varying(255),
    receiveddate date,
    pursuit character varying(255),
    masse character varying(255),
    relay character varying(255),
    distance character varying(255),
    hill integer,
    style character varying(255),
    qualif character varying(255),
    finale character varying(255),
    homol character varying(255),
    webcomment character varying(255),
    displaystatus character varying(255),
    fisinterncomment character varying(255),
    published integer,
    validforfispoints integer,
    usedfislist character varying(255),
    tolist character varying(255),
    discforlistcode character varying(255),
    calculatedpenalty character varying(255),
    appliedpenalty character varying(255),
    appliedscala character varying(255),
    penscafixed character varying(255),
    version integer,
    nationraceid integer,
    provraceid integer,
    msql7evid integer,
    mssql7id integer,
    results integer,
    pdf integer,
    topbanner character varying(255),
    bottombanner character varying(255),
    toplogo character varying(255),
    bottomlogo character varying(255),
    gallery character varying(255),
    indi integer,
    team integer,
    tabcount integer,
    columncount integer,
    level character varying(255),
    hloc1 time without time zone,
    hloc2 time without time zone,
    hloc3 time without time zone,
    hcet1 time without time zone,
    hcet2 time without time zone,
    hcet3 time without time zone,
    live integer,
    livestatus1 character varying(255),
    livestatus2 character varying(255),
    livestatus3 character varying(255),
    liveinfo1 character varying(255),
    liveinfo2 character varying(255),
    liveinfo3 character varying(255),
    passwd character varying(255),
    timinglogo character varying(255),
    validdate date,
    noepr integer,
    tddoc integer,
    timingreport integer,
    special_cup_points integer,
    skip_wcsl integer,
    lastupdate timestamp without time zone
);


--
-- Name: a_racenk; Type: TABLE; Schema: public; Owner: fislocal
--

CREATE TABLE public.a_racenk (
    raceid integer,
    eventid integer,
    seasoncode integer,
    racecodex integer,
    disciplineid character varying(255),
    disciplinecode character varying(255),
    catcode character varying(255),
    catcode2 character varying(255),
    catcode3 character varying(255),
    catcode4 character varying(255),
    gender character varying(255),
    racedate date,
    starteventdate date,
    description character varying(255),
    place character varying(255),
    nationcode character varying(10),
    td1id integer,
    td1name character varying(255),
    td1nation character varying(255),
    td1code integer,
    td2id integer,
    td2name character varying(255),
    td2nation character varying(255),
    td2code integer,
    calstatuscode character varying(255),
    procstatuscode character varying(255),
    receiveddate date,
    pursuit character varying(255),
    masse character varying(255),
    relay character varying(255),
    distance character varying(255),
    hill integer,
    style character varying(255),
    qualif character varying(255),
    finale character varying(255),
    homol character varying(255),
    webcomment character varying(255),
    displaystatus character varying(255),
    fisinterncomment character varying(255),
    published integer,
    validforfispoints integer,
    usedfislist character varying(255),
    tolist character varying(255),
    discforlistcode character varying(255),
    calculatedpenalty character varying(255),
    appliedpenalty character varying(255),
    appliedscala character varying(255),
    penscafixed character varying(255),
    version integer,
    nationraceid integer,
    provraceid integer,
    msql7evid integer,
    mssql7id integer,
    results integer,
    pdf integer,
    topbanner character varying(255),
    bottombanner character varying(255),
    toplogo character varying(255),
    bottomlogo character varying(255),
    gallery character varying(255),
    indi integer,
    team integer,
    tabcount integer,
    columncount integer,
    level character varying(255),
    hloc1 time without time zone,
    hloc2 time without time zone,
    hloc3 time without time zone,
    hcet1 time without time zone,
    hcet2 time without time zone,
    hcet3 time without time zone,
    live integer,
    livestatus1 character varying(255),
    livestatus2 character varying(255),
    livestatus3 character varying(255),
    liveinfo1 character varying(255),
    liveinfo2 character varying(255),
    liveinfo3 character varying(255),
    passwd character varying(255),
    timinglogo character varying(255),
    validdate date,
    noepr integer,
    tddoc integer,
    timingreport integer,
    special_cup_points integer,
    skip_wcsl integer,
    validforowg integer,
    lastupdate timestamp without time zone
);

--
-- Name: a_resultjp; Type: TABLE; Schema: public; Owner: fislocal
--

CREATE TABLE public.a_resultjp (
    recid integer,
    raceid integer,
    competitorid integer,
    status character varying(255),
    status2 character varying(255),
    "position" integer,
    bib integer,
    fiscode integer,
    competitorname character varying(255),
    nationcode character varying(255),
    level character varying(255),
    heat character varying(255),
    stage character varying(255),
    j1r1 character varying(255),
    j2r1 character varying(255),
    j3r1 character varying(255),
    j4r1 character varying(255),
    j5r1 character varying(255),
    speedr1 numeric(10,5),
    distr1 character varying(255),
    disptsr1 numeric(10,5),
    judptsr1 numeric(10,5),
    totrun1 character varying(255),
    posr1 integer,
    statusr1 character varying(255),
    j1r2 character varying(255),
    j2r2 character varying(255),
    j3r2 character varying(255),
    j4r2 character varying(255),
    j5r2 character varying(255),
    speedr2 numeric(10,5),
    distr2 character varying(255),
    disptsr2 numeric(10,5),
    judptsr2 numeric(10,5),
    totrun2 character varying(255),
    posr2 integer,
    statusr2 character varying(255),
    j1r3 character varying(255),
    j2r3 character varying(255),
    j3r3 character varying(255),
    j4r3 character varying(255),
    j5r3 character varying(255),
    speedr3 numeric(10,5),
    distr3 character varying(255),
    disptsr3 numeric(10,5),
    judptsr3 numeric(10,5),
    totrun3 character varying(255),
    posr3 integer,
    statusr3 character varying(255),
    j1r4 character varying(255),
    j2r4 character varying(255),
    j3r4 character varying(255),
    j4r4 character varying(255),
    j5r4 character varying(255),
    speedr4 numeric(10,5),
    distr4 character varying(255),
    disptsr4 numeric(10,5),
    judptsr4 numeric(10,5),
    gater1 integer,
    gater2 integer,
    gater3 integer,
    gater4 integer,
    gateptsr1 numeric(10,5),
    gateptsr2 numeric(10,5),
    gateptsr3 numeric(10,5),
    gateptsr4 numeric(10,5),
    windr1 numeric(10,5),
    windr2 numeric(10,5),
    windr3 numeric(10,5),
    windr4 numeric(10,5),
    windptsr1 numeric(10,5),
    windptsr2 numeric(10,5),
    windptsr3 numeric(10,5),
    windptsr4 numeric(10,5),
    reason character varying(255),
    totrun4 character varying(255),
    tot numeric(10,5),
    valid integer,
    racepoints numeric(10,5),
    cuppoints numeric(10,5),
    version character varying(255),
    lastupdate timestamp without time zone,
    posr4 integer,
    statusr4 character varying(255)
);

--
-- Name: a_resultnk; Type: TABLE; Schema: public; Owner: fislocal
--

CREATE TABLE public.a_resultnk (
    recid integer,
    raceid integer,
    competitorid integer,
    status character varying(255),
    reason character varying(255),
    "position" integer,
    pf integer,
    status2 character varying(255),
    bib integer,
    bibcolor character varying(255),
    fiscode integer,
    competitorname character varying(255),
    nationcode character varying(255),
    level character varying(255),
    heat character varying(255),
    stage character varying(255),
    j1r1 character varying(255),
    j2r1 character varying(255),
    j3r1 character varying(255),
    j4r1 character varying(255),
    j5r1 character varying(255),
    speedr1 numeric(10,5),
    distr1 numeric(10,5),
    disptsr1 numeric(10,5),
    judptsr1 numeric(10,5),
    gater1 integer,
    gateptsr1 numeric(10,5),
    windr1 numeric(10,5),
    windptsr1 numeric(10,5),
    totrun1 numeric(10,5),
    posr1 integer,
    statusr1 character varying(255),
    j1r2 character varying(255),
    j2r2 character varying(255),
    j3r2 character varying(255),
    j4r2 character varying(255),
    j5r2 character varying(255),
    speedr2 numeric(10,5),
    distr2 character varying(255),
    disptsr2 numeric(10,5),
    judptsr2 numeric(10,5),
    gater2 integer,
    gateptsr2 numeric(10,5),
    windr2 numeric(10,5),
    windptsr2 numeric(10,5),
    totrun2 character varying(255),
    posr2 integer,
    statusr2 character varying(255),
    pointsjump numeric(10,5),
    behindjump character varying(255),
    posjump integer,
    timecc character varying(255),
    timeccint character varying(255),
    poscc integer,
    starttime character varying(255),
    statuscc character varying(255),
    totbehind character varying(255),
    timetot character varying(255),
    timetotint integer,
    valid integer,
    racepoints numeric(10,5),
    cuppoints numeric(10,5),
    version character varying(255),
    lastupdate timestamp without time zone
);
